
services:
  - type: web
    name: ai-advisor-agent
    rootDir: api
    env: go
    buildCommand: "go build -o server ."
    startCommand: "./server"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_BASE_URL
        fromService:
          type: web
          name: ai-advisor-agent
          property: url
      - key: CRON_TOKEN
        sync: false
